const logos = [
    'Discord link for quickest updates of your favorite novels: https://discord.gg/novelcommunity',
    '<p> ?α?dαηθνε| </p>',
    'ƥαṇdαηθνε|',
    'ƥαṇdα- ηθνε|·ƈθm',
    'ƥαṇdα-ηθνε|·ƈθm',
    'panda novel',
    'ραпdα -n૦νe| , c૦m',
    'ραпdαn૦νel',
    'ραпdα- n૦νe|`c,0m',
    'eαglesnovel`c,om',
    'eαglesn૦νel',
    'ραпdα---n૦νa| сom',
    'pαndα`noνɐ1--сoМ',
    'ραпdα nᴏνa| сom',
    'pαndα,noνɐ1,сoМ',
    'ραпdα nᴏνɐ| сom ***',
    'pαпdα`noνɐ1`сoМ',
    'pαndα`noνɐ1~сoМ',
    'pαndα`noνɐ1~сoМ',
    'pαпdαnoνɐ1сoМ',
    'ραпdα `nᴏνɐ| сom',
    'ραпdα nᴏνɐ| сom',
    'pαпᵈα-noνɐ1·сoМ',
    'pαпdα Й?νê|,сòМ',
    'please visit pαпᵈα-:)ɴᴏᴠᴇ1.co)m',
    'pαndα noνɐ1,сoМ',
    'pαndα noνɐ1,сoМ',
    'pαпᵈα-noνɐ1.сoМ',
    'ραпdα-nᴏνɐ|-сom',
    'pαndα-noνɐ1,сoМ',
    'pαndα noνɐ1,сoМ',
    '<novelsnext>please visit p\u03B1\u043F\u1D48\u03B1-:)\u0274\u1D0F\u1D20\u1D071.co)m<\/novelsnext>',
    'ραпdα nᴏνɐ| сom',
    'pαпᵈα-:)ɴᴏᴠᴇ1.co)m',
    'ραпdα Йᴏνê|(сòm)',
    '<p>　&nbsp;　</p>',
    '<p>　　　 </p>',
    '<p>　　　 </p>',
    '<p>　　　　　　 </p>',
    '<p>　　　　　　 </p>',
    '<p>　　 </p>',
    '<p>　　 </p>',
    'pαпdα-ňᴏνêι·сóМ',
    'pǎпdǎ Йᴏνê1,сòМ',
    'ραпdα Йᴏνêl(сòm)',
    'ραпdα Йᴏνêl(сòm)',
    'ραпdǎ Йᴏνêl(сòm)',
    'pαпdα Йᴏνê1,сòМ',
    'pA ɴ,da-nᴏᴠᴇʟ.cᴏm',
    'pAn,D a-ɴᴏᴠ ᴇ1,c-o-m',
    'p An dD ɴᴏᴠᴇ1.cO,,m',
    '<novelsnext>please visit panda-:)ɴᴏᴠᴇ1.co)m</novelsnext>',
    'p、A,nd , A-n、o、ve,1',
    'please visit panda-:)ɴᴏᴠᴇ1.co)m',
    'p-A- n-d-A--n-0-v--e-1、(com',
    'p-n0v,e1、c--o-m',
    'pAn,D a-ɴᴏᴠ ᴇ1,c-o-m',
    'pA ɴ,da-nᴏᴠᴇʟ.cᴏm',
    'please visit panda-:)ɴᴏᴠᴇ1.co)m',
    '<novelsnext>please visit panda-:)ɴᴏᴠᴇ1.co)m</novelsnext>',
    'pA ɴ,da-nᴏᴠᴇʟ.cᴏm',
    'pAn,Da n&lt;0,&gt;v,e1',
    'pAnD a(-)n0ve1.com',
    'pAn,Da n<0,>v,e1',
    'please visit p(anda-n0ve1.co)m',
    'p Anda nOve1.cO,m',
    'pA n,dan(-)0ve1.c0m',
    'p AndD nOve1.cO,m',
    'pAn,D a-n0ve1,c-o-m',
    'pAn,Da-n0v e1,c',
    'pA(nd)A no ve1',
    'pAn,da n<0,>v,e1',
    'p AndD nOve1.cO,m',
    'pA(nD)A no ve1',
    'please visit panda(-)N0ve1.co)m',
    'panda(-)N0ve1.co)m',
    'pAnDa (nov)e1',
    'pAn,da n&lt;0,&gt;v,e1',
    'p Anda nOve1.cO,m',
    'pAn,da n<0,>v,e1',
    'pAn,da n<0,>v,e1',
    'pand(a-n0vel.c)om',
    'pand(a-n0vel.c)om',
    'pAn-d a-n0ve1.com',
    'pA n,dan0ve1.c0m',
    'pAnda (nov)e1',
    'pAn,da-n0v e1,c',
    'p、A,nd A-n、o、ve,1',
    'p-A- n-d-A-n-0-v-e-1、(c)om',
    'pan(da-n0vel.c)om',
    'pan(da-n0vel.c)om',
    'pan-d a-n0vel.com',
    'For more chapters, please visit',
    'panda-n(0ve)l.com',
    'pandan(o)vel',
    'panda n(O)vel',
    'panda-n(0ve)l.com',
    'panda-n(0ve)l.com',
    'panda (nov)el',
    'A quick look at FreeWebNovel.Com will leave you more fulfilled.',
    'panda novel',
    'Panda Novel',
    'pAn-d a-n0ve1.com',
    'panda-n( 0 ve)l.com',
    'pan,da-n0v el,c',
    'pan,da-n0v el,c,m',
    'p anda nOvel.cO,m',
    'p anda nOvel.cO,m',
    'pan-d a-n0vel.com',
    'p-a- n-d-a-n-0-v-e-l、(c)om',
    'pA n,dan0vel.c0m',
    'pa(nd)a no vel',
    'pan,d a-n0vel,c-o-m',
    'pan,da-n0v el,c,m',
    'p、a,nd a-n、o、ve,l',
    'p-n0vel、com',
    '<o>,m',
    '</o>',
    'pan,da n<0,>v,el',
    'pan,da-n0v el,c,m',
    'pa(nd)a no vel',
    'pan,d a-n0vel,c-o-m',
    'For more chapters, please visit panda-n( 0 ve)l.com',
    'p-a- n-d-a-n-0-v-e-l、(c)om',
    'pan-d a-n0vel.com',
    'pan-d a-n0vel.com',
    'pan-d a-n0vel.com',
    'p-a- n-d-a-n-0-v-e-l、(c)om',
    'p-a- n-d-a-n-0-v-e-l、(c)om',
    'pA n,dan0vel.c0m',
    'ᴘᴀɴ ᴅᴀ ɴ ᴏᴠᴇʟ',
    'pa(nd)a novel',
    'pan,da n<0,>v,el',
    'pan,da n<0,>v,el',
    '-n0vel、com',
    'panda nOvel.cO,m',
    'pan,da-n0vel,c,m',
    'pᴀɴᴅᴀ ɴ(O)ᴠᴇʟ',
    'ρꪖꪕᦔꪖꪕ(ꪫ)ꪣꫀ​ꪶ',
    'p<ᴀɴᴅ>ᴀ-ɴ0ᴠᴇʟ',
    'p<ᴀɴᴅ>ᴀ-ɴ0ᴠᴇʟ、ᴄᴏᴍ',
    'ρꪖnᦔa (nꪫ)ꪣꫀ​ꪶ',
    'p-ᴀ-ɴ-ᴅ-ᴀ ɴ-0-ᴠ-ᴇ-ʟ、ᴄ(ᴏᴍ)',
    'For more chapters, please visit panda-n(0ve)l.com',
    'pan,da n<0,>v,el',
    'pan,da-n0vel,c-o-m',
    'p、a,nd a-n、o、ve,l',
    'panda (nov)el',
    'pan,da-n0vel,c',
    'pAn,dan0vel.c0m',
    'pan-da-n0vel.com',
    'p、a,nd a-n、o、ve,l',
    'p-n0vel、com',
    'pan,da-n0vel,c-o-m',
    'pan,da-n0vel,c,m',
    'p-a-n-d-a-n-0-v-e-l、(c)om',
    'panda (nov)el',
    'pan,da n<0,>v,el',
    'pan,da n&lt;0,&gt;v,el',
    'p<anda>',
    '</anda>',
    '-n0ve1、com'
]

module.exports = logos;